version: '0.6'
services:
  
  # postgres:
  #   image: postgres:alpine
  #   container_name: postgres
  #   environment:
  #     POSTGRES_DB : postgres
  #     POSTGRES_USER : postgres
  #     POSTGRES_PASSWORD : aithe
  #     POSTGRES_HOST_AUTH_METHOD : trust
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - postgres-data:/data/db
  
  backend_dev:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file: 
      - ./backend/.env
    ports:
      - "8000:8000"
    # environment:
    #   DB_NAME: postgres
    #   DB_USER: postgres
    #   DB_PASSWORD: aithe
    #   DB_HOST: localhost  
    #   # POSTGRES_URL: postgresql://postgres:aithe@localhost:5432/postgres
    # depends_on:
    #   - postgres  
  
  react_dev:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    env_file:
      - ./frontend/.env.development
    ports:
      - "3000:3000"
    environment:
      REACT_APP_URL: http://localhost:3000  
  
volumes:
  postgres-data: