version: '3.8'
services:  

  backend_dev:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file: 
      - ./backend/.env
    ports:
      - "8000:8000"
    networks:
      - app_network
    environment:
      OLLAMA_BASE_URL: http://ollama_dev:11434
  
  react_dev:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    env_file:
      - ./frontend/.env.development
    ports:
      - "3000:3000"
    environment:
      REACT_APP_URL: http://localhost:3000  
    networks:
      - app_network

  ollama_dev:
    build:
      context: ./ollama
      dockerfile: Dockerfile
    ports:
      - "11434:11434"
    volumes:
      - ./ollama/models:/models

networks:
  app_network:
    driver: bridge      

# docker-compose -f docker-compose-dev.yml up -d --build      
# docker-compose -f docker-compose-dev.yml up --build      