version: '3.8'
services:  
  backend_dev:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file: 
      - ./backend/.env
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app                    # 소스 코드 마운트
      - ./vector_store:/app/vector_store  # 벡터 스토어 마운트
    networks:
      - app_network
    environment:
      OLLAMA_BASE_URL: http://ollama_dev:11434
    # 컨테이너가 계속 실행되도록 설정
    tty: true
    stdin_open: true
  
  react_dev:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    env_file:
      - ./frontend/.env.development
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      REACT_APP_URL: http://61.108.166.16:3000
      REACT_APP_API_URL: http://61.108.166.16:8000
      DISABLE_ESLINT_PLUGIN: "true"
      CI: "false"
    networks:
      - app_network

  ollama_dev:
    build:
      context: ./ollama
      dockerfile: Dockerfile
    ports:
      - "11434:11434"
    volumes:
      - ./ollama/models:/models
    networks:
      - app_network             

networks:
  app_network:
    driver: bridge      

# docker-compose -f docker-compose-dev.yml up --build      