version: "3"

services:
  bnh_poc_n8n:
    image: n8nio/n8n:latest
    container_name: bnh_poc_n8n
    restart: always
    ports:
      - "15678:5678"
    environment:
      - N8N_SECURE_COOKIE=false
      - N8N_BASIC_AUTH_ACTIVE=false
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=1q1q!Q!Q  ## 패스워드를 변경해주세요!!
      - GENERIC_TIMEZONE=Asia/Seoul
      - TZ=Asia/Seoul
    volumes:
      - n8n_data:/data/bnh/n8n/.n8n

volumes:
  n8n_data: